<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Loom.Integrations</RootNamespace>
    <AssemblyName>Loom.Integrations</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loom.Application\Loom.Application.csproj" />
    <ProjectReference Include="..\Loom.Domain\Loom.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
