// <auto-generated />
using Loom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Loom.Infrastructure.Persistence.Migrations
{
    // Designer companion for the hand-authored Initial migration. EF Core
    // requires the [Migration(...)] attribute (which lives on a Designer
    // partial) to enrol a migration class in the apply pipeline; without
    // it, MigrateAsync silently skips Initial and tries to apply Workflow
    // first, which fails because loom.runs doesn't exist yet.
    //
    // BuildTargetModel only matters for `dotnet ef migrations add` diffs
    // and is intentionally minimal here — the authoritative post-Initial
    // model state is captured by the next migration's Designer
    // (20260503091512_Workflow.Designer.cs) plus
    // LoomDbContextModelSnapshot.cs.
    [DbContext(typeof(LoomDbContext))]
    [Migration("20260502_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loom")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
