// <auto-generated />
using System;
using System.Collections.Generic;
using Loom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoomDbContext))]
    [Migration("20260505195714_SubscriptionsProjectAndRole")]
    partial class SubscriptionsProjectAndRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loom")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loom.Domain.Annotations.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("annotations", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("NodeId");

                    b.ToTable("artifacts", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Artifacts.ArtifactVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("artifact_versions", "loom");
                });

            modelBuilder.Entity("Loom.Domain.BudgetControl.ProjectBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DailyCapUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("DayAnchor")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TodaysSpendUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("project_budgets", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("RunId");

                    b.ToTable("conversations", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("messages", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Fragments.Fragment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.PrimitiveCollection<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key", "Scope", "ScopeId")
                        .IsUnique()
                        .HasFilter("[ScopeId] IS NOT NULL");

                    b.ToTable("fragments", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Fragments.FragmentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FragmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FragmentId", "Version")
                        .IsUnique();

                    b.ToTable("fragment_versions", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Integrations.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastHealthCheckAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecretRef")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantOrAccount")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "ProjectId");

                    b.ToTable("integration_connections", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Integrations.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ConnectionId", "ReceivedAt");

                    b.ToTable("webhook_deliveries", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Nodes.FeatureNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Intent")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.PrimitiveCollection<string>("_openQuestions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("open_questions");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique();

                    b.ToTable("nodes", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Nodes.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("projects", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeepLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.ToTable("notifications", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Notifications.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "EventType");

                    b.HasIndex("ProjectId", "EventType");

                    b.HasIndex("UserId", "NodeId", "ProjectId", "EventType", "Channel", "Role")
                        .IsUnique()
                        .HasFilter("[NodeId] IS NOT NULL AND [ProjectId] IS NOT NULL AND [Role] IS NOT NULL");

                    b.ToTable("subscriptions", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Runs.AssembledPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssembledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OutputSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_fragments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fragments");

                    b.Property<string>("_messages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messages");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("assembled_prompts", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssembledPromptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Engine")
                        .HasColumnType("int");

                    b.Property<string>("ExternalRunId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Budgets", "Loom.Domain.Runs.Run.Budgets#Budgets", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("MaxCostUsd")
                                .HasPrecision(10, 4)
                                .HasColumnType("decimal(10,4)")
                                .HasColumnName("budgets_max_cost_usd");

                            b1.Property<int?>("MaxInputTokens")
                                .HasColumnType("int")
                                .HasColumnName("budgets_max_input_tokens");

                            b1.Property<int?>("MaxOutputTokens")
                                .HasColumnType("int")
                                .HasColumnName("budgets_max_output_tokens");

                            b1.Property<TimeSpan?>("MaxWallClock")
                                .HasColumnType("time")
                                .HasColumnName("budgets_max_wall_clock");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "Loom.Domain.Runs.Run.Cost#Cost", b1 =>
                        {
                            b1.Property<string>("Deployment")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("cost_deployment");

                            b1.Property<int>("InputTokens")
                                .HasColumnType("int")
                                .HasColumnName("cost_input_tokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("cost_model");

                            b1.Property<int>("OutputTokens")
                                .HasColumnType("int")
                                .HasColumnName("cost_output_tokens");

                            b1.Property<decimal>("UsdAmount")
                                .HasPrecision(10, 4)
                                .HasColumnType("decimal(10,4)")
                                .HasColumnName("cost_usd_amount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("State");

                    b.HasIndex("AssigneeUserId", "State");

                    b.ToTable("runs", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Runs.RunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("run_events", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Runs.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("transcripts", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Workflows.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("workflows", "loom");
                });

            modelBuilder.Entity("Loom.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("outbox", "loom");
                });

            modelBuilder.Entity("Loom.Domain.Annotations.Annotation", b =>
                {
                    b.OwnsOne("Loom.Domain.Annotations.AnnotationTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("AnnotationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("target_kind");

                            b1.Property<string>("Locator")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("target_locator");

                            b1.HasKey("AnnotationId");

                            b1.ToTable("annotations", "loom");

                            b1.WithOwner()
                                .HasForeignKey("AnnotationId");
                        });

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Loom.Domain.Artifacts.Artifact", b =>
                {
                    b.OwnsOne("Loom.Domain.Artifacts.ArtifactLock", "Lock", b1 =>
                        {
                            b1.Property<Guid>("ArtifactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("AcquiredAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("lock_acquired_at");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("lock_expires_at");

                            b1.Property<Guid>("HolderUserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("lock_holder_user_id");

                            b1.HasKey("ArtifactId");

                            b1.ToTable("artifacts", "loom");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactId");
                        });

                    b.OwnsOne("Loom.Domain.Artifacts.CanonicalPointer", "Canonical", b1 =>
                        {
                            b1.Property<Guid>("ArtifactId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("canonical_external_id");

                            b1.Property<int>("Store")
                                .HasColumnType("int")
                                .HasColumnName("canonical_store");

                            b1.Property<string>("Url")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("canonical_url");

                            b1.HasKey("ArtifactId");

                            b1.ToTable("artifacts", "loom");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactId");
                        });

                    b.Navigation("Canonical")
                        .IsRequired();

                    b.Navigation("Lock");
                });

            modelBuilder.Entity("Loom.Domain.Artifacts.ArtifactVersion", b =>
                {
                    b.HasOne("Loom.Domain.Artifacts.Artifact", null)
                        .WithMany("Versions")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Loom.Domain.Artifacts.BlobRef", "Content", b1 =>
                        {
                            b1.Property<Guid>("ArtifactVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("content_type");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("content_size_bytes");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("content_uri");

                            b1.HasKey("ArtifactVersionId");

                            b1.ToTable("artifact_versions", "loom");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactVersionId");
                        });

                    b.OwnsOne("Loom.Domain.Artifacts.BlobRef", "Preview", b1 =>
                        {
                            b1.Property<Guid>("ArtifactVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("preview_content_type");

                            b1.Property<long?>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("preview_size_bytes");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("preview_uri");

                            b1.HasKey("ArtifactVersionId");

                            b1.ToTable("artifact_versions", "loom");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactVersionId");
                        });

                    b.OwnsOne("Loom.Domain.Artifacts.Author", "Author", b1 =>
                        {
                            b1.Property<Guid>("ArtifactVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("author_id");

                            b1.Property<int>("Kind")
                                .HasColumnType("int")
                                .HasColumnName("author_kind");

                            b1.HasKey("ArtifactVersionId");

                            b1.ToTable("artifact_versions", "loom");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactVersionId");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Loom.Domain.Conversations.Message", b =>
                {
                    b.HasOne("Loom.Domain.Conversations.Conversation", null)
                        .WithMany("_messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Loom.Domain.Conversations.MessageAuthor", "Author", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Kind")
                                .HasColumnType("int")
                                .HasColumnName("author_kind");

                            b1.Property<Guid?>("RunId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("author_run_id");

                            b1.Property<Guid?>("UserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("author_user_id");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages", "loom");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });

            modelBuilder.Entity("Loom.Domain.Fragments.FragmentVersion", b =>
                {
                    b.HasOne("Loom.Domain.Fragments.Fragment", null)
                        .WithMany("_versions")
                        .HasForeignKey("FragmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Loom.Domain.Fragments.EngineHints", "Hints", b1 =>
                        {
                            b1.Property<Guid>("FragmentVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("MaxContextTokens")
                                .HasColumnType("int")
                                .HasColumnName("hints_max_context_tokens");

                            b1.Property<string>("PreferredModelHint")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("hints_preferred_model");

                            b1.Property<bool>("PrefersExtendedThinking")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("hints_prefers_extended_thinking");

                            b1.Property<bool>("RequiresFilesystem")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("hints_requires_filesystem");

                            b1.Property<bool>("RequiresJsonOutput")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("hints_requires_json_output");

                            b1.HasKey("FragmentVersionId");

                            b1.ToTable("fragment_versions", "loom");

                            b1.WithOwner()
                                .HasForeignKey("FragmentVersionId");
                        });

                    b.Navigation("Hints")
                        .IsRequired();
                });

            modelBuilder.Entity("Loom.Domain.Nodes.FeatureNode", b =>
                {
                    b.HasOne("Loom.Domain.Nodes.FeatureNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Loom.Domain.Nodes.Constraint", "_constraints", b1 =>
                        {
                            b1.Property<Guid>("node_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ordinal"));

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<int>("Kind")
                                .HasColumnType("int");

                            b1.HasKey("node_id", "ordinal");

                            b1.ToTable("node_constraints", "loom");

                            b1.WithOwner()
                                .HasForeignKey("node_id");
                        });

                    b.OwnsMany("Loom.Domain.Nodes.Hypothesis", "_hypotheses", b1 =>
                        {
                            b1.Property<Guid>("node_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ordinal"));

                            b1.Property<string>("Because")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("If")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Then")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("node_id", "ordinal");

                            b1.ToTable("node_hypotheses", "loom");

                            b1.WithOwner()
                                .HasForeignKey("node_id");
                        });

                    b.OwnsMany("Loom.Domain.Nodes.Outcome", "_outcomes", b1 =>
                        {
                            b1.Property<Guid>("node_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ordinal"));

                            b1.Property<bool>("Measurable")
                                .HasColumnType("bit");

                            b1.Property<string>("MetricHint")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Statement")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("node_id", "ordinal");

                            b1.ToTable("node_outcomes", "loom");

                            b1.WithOwner()
                                .HasForeignKey("node_id");
                        });

                    b.OwnsMany("Loom.Domain.Nodes.Stakeholder", "_stakeholders", b1 =>
                        {
                            b1.Property<Guid>("node_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ordinal"));

                            b1.Property<string>("Interest")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid?>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("node_id", "ordinal");

                            b1.ToTable("node_stakeholders", "loom");

                            b1.WithOwner()
                                .HasForeignKey("node_id");
                        });

                    b.Navigation("_constraints");

                    b.Navigation("_hypotheses");

                    b.Navigation("_outcomes");

                    b.Navigation("_stakeholders");
                });

            modelBuilder.Entity("Loom.Domain.Runs.Run", b =>
                {
                    b.OwnsMany("Loom.Domain.Runs.FragmentRef", "_fragments", b1 =>
                        {
                            b1.Property<Guid>("run_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ordinal"));

                            b1.Property<Guid>("FragmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Version")
                                .HasColumnType("int");

                            b1.Property<Guid>("VersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("run_id", "ordinal");

                            b1.ToTable("run_fragments", "loom");

                            b1.WithOwner()
                                .HasForeignKey("run_id");
                        });

                    b.Navigation("_fragments");
                });

            modelBuilder.Entity("Loom.Domain.Workflows.Workflow", b =>
                {
                    b.OwnsMany("Loom.Domain.Workflows.WorkflowStep", "_steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("EnginePref")
                                .HasColumnType("int");

                            b1.Property<int>("Gating")
                                .HasColumnType("int");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.Property<int>("Kind")
                                .HasColumnType("int");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("OutputSchemaName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("_fragmentSelectors")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("selectors");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowId", "Order");

                            b1.ToTable("workflow_steps", "loom");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");

                            b1.OwnsOne("Loom.Domain.Runs.Budgets", "Budgets", b2 =>
                                {
                                    b2.Property<Guid>("WorkflowStepId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal?>("MaxCostUsd")
                                        .HasPrecision(10, 4)
                                        .HasColumnType("decimal(10,4)")
                                        .HasColumnName("budgets_max_cost_usd");

                                    b2.Property<int?>("MaxInputTokens")
                                        .HasColumnType("int")
                                        .HasColumnName("budgets_max_input_tokens");

                                    b2.Property<int?>("MaxOutputTokens")
                                        .HasColumnType("int")
                                        .HasColumnName("budgets_max_output_tokens");

                                    b2.Property<TimeSpan?>("MaxWallClock")
                                        .HasColumnType("time")
                                        .HasColumnName("budgets_max_wall_clock");

                                    b2.HasKey("WorkflowStepId");

                                    b2.ToTable("workflow_steps", "loom");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkflowStepId");
                                });

                            b1.Navigation("Budgets")
                                .IsRequired();
                        });

                    b.Navigation("_steps");
                });

            modelBuilder.Entity("Loom.Domain.Artifacts.Artifact", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Loom.Domain.Conversations.Conversation", b =>
                {
                    b.Navigation("_messages");
                });

            modelBuilder.Entity("Loom.Domain.Fragments.Fragment", b =>
                {
                    b.Navigation("_versions");
                });
#pragma warning restore 612, 618
        }
    }
}
