<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Loom.Domain</RootNamespace>
    <AssemblyName>Loom.Domain</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Loom.Domain.Tests" />
  </ItemGroup>

</Project>
