using System.Globalization;
using System.Text;
using Loom.Domain.Fragments;

namespace Loom.Integrations.GitSync;

/// <summary>
/// Pure compiler from a fragment set to the two file payloads written into
/// every Loom-aware repo: <c>CLAUDE.md</c> and <c>.cursorrules</c>. Phase 2
/// renders them identically; Phase 7 will diverge if Cursor introduces a
/// format Claude Code won't accept.
/// </summary>
public static class FragmentRulesCompiler
{
    public const string ClaudeFile = "CLAUDE.md";
    public const string CursorFile = ".cursorrules";

    public static string Compile(IEnumerable<Fragment> fragments, string projectName)
    {
        ArgumentNullException.ThrowIfNull(fragments);
        var inv = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();

        sb.Append("# Loom rules — ").AppendLine(projectName);
        sb.AppendLine("# Auto-generated by Loom GitSync. DO NOT EDIT BY HAND — edit the source");
        sb.AppendLine("# fragment in the Loom Fragment Library and a new version of this file");
        sb.AppendLine("# will be written on next sync.");
        sb.AppendLine();

        var ordered = fragments
            .Where(f => f.CurrentVersion is not null && !f.CurrentVersion.IsDeprecated)
            .Where(f => f.Category is FragmentCategory.Identity
                or FragmentCategory.Methodology
                or FragmentCategory.Project
                or FragmentCategory.Domain
                or FragmentCategory.Skill)
            .OrderBy(f => (int)f.Category)
            .ThenBy(f => f.Key.Value, StringComparer.Ordinal);

        foreach (var f in ordered)
        {
            sb.Append("## ").Append(f.Category).Append(": ").AppendLine(f.Title);
            sb.AppendLine(inv, $"<!-- {f.Key.Value} v{f.CurrentVersion!.Version} (scope: {f.Scope}) -->");
            sb.AppendLine(f.CurrentVersion.Content.TrimEnd());
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }
}
